---
title: "Untitled"
author: "Ian"
date: "October 17, 2018"
output: html_document
---
#### **Data Sources**

Bezerra, T.R., Domingues, E.C., Filho, L.F.A.M., Rombenso, A.N., Hamilton, S., & Cavalli, R.O, (2015). Economic analysis of cobia (*Rachycnetron canadum*) cage culture in large- and small-scale production systems in Brazil. *Aquaculture International*, **24**, 1-14.DOI: 10.1007/s10499-015-9951-2     

Karayucel, S. and Karayucel, I. (2000). the effect of environmental factors, depth and position on the growth and mortality of raft-cultured blue mussels (*Mytilus edulis* L.). *Aquaculture Research*, **31**, 893-899. DOI: 10.1046/j.1365-2109.2000.00496.x

Ladner, I., Su, I., Wolfe, S., & Oliver, S. (2018). *Economic feasibility of seaweed aquaculture in Southern California.* (Unpublished master's thesis). University of California Santa Barbara, Santa Barbara, CA.

Lester, S.E., Stevens, J.M., Gentry, R.R., Kappel, C.V., Bell, T.W., Costello, C.J., Gaines, S.D., Kiefer, D.A., Maue, C.C., Simons, R.D., Washburn, L., & White, C. (2018). Marine spatial planing makes rooms for offshore aquaculture in crowded coastal waters. *Nature Communications*, **9**. DOI: 10.1038/s41467-018-03249-1

Lindell, S. (2017). Workshop 6: becoming a VSE shellfish producer. Prepared for the Ventura Shellfish Enterprise. https://vimeo.com/221384151  

Watson, L., & Dring, M. (2011). Business plan for the establishment of a seaweed hatchery and grow-out farm. Prepared for the *Irish Sea Fisheries Board.*
